import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "../context/ThemeContext";
import Navbar from "@/components/component/Navbar";
import Footer from "@/components/component/Footer";
import ContextProvider from "@/context";
import { headers } from "next/headers";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookies = (await headers()).get("cookie");

  return (
    <ThemeProvider>
      <html lang="en">
        <body
          className={`bg-light-background dark:bg-dark-background text-light-text dark:text-dark-text ${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
        >
          <ContextProvider cookies={cookies}>
            <Navbar />
            <div className="mx-auto min-h-[80vh] px-2 py-4 max-w-[1440px]">
              {children}
            </div>
            <Footer />
            <ToastContainer />
          </ContextProvider>
        </body>
      </html>
    </ThemeProvider>
  );
}
